- name: Add repository Java 8
  apt_repository:
    repo: "ppa:webupd8team/java"
    state: present

- name: Accept Java 8 License
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: Install Java 8
  apt:
    name: oracle-java8-installer
    state: present

