
- hosts: all
  vars:
    repos_dir: /vagrant
    db_model_config_file: '${ repos_dir}/ansible/properties/training.properties'
    db_model:
        name: rest-training
        user: postgres
        pass: postgre
        host: 'jdbc:postgresql://localhost:5432/rest-training'
  environment:
    JAVA_HOME: "/usr/lib/jvm/java-8-oracle"
    JRE_HOME: "/usr/lib/jvm/java-8-oracle/jre"
  become: yes

  pre_tasks:
    - import_tasks: java.yml
    - import_tasks: maven.yml


  roles:
    - role: postgresql
      vars:
          postgresql_role_name: '{{ db_model.user }}'
          postgresql_role_password: '{{ db_model.pass }}'
          postgresql_database_name: '{{ db_model.name }}'
          postgresql_privileges_type: database
          postgresql_privileges_privs: ALL
          postgresql_pghba_rules:
              - type: local
                method: trust
              - type: host
                address: 127.0.0.1/32
                method: trust

  tasks:
    - name: 
      lineinfile:
          dest: '{{ db_model_config_file }}'
          regexp: '^{{ item.key }}[ \t]+=[ \t]+.*$'
          line: '{{ item.key }} = {{ item.value }}'
      with_items:
          - key: jdbc.url
            value: '{{ db_model.host }}'
          - key: jdbc.username
            value: '{{ db_model.user }}'
          - key: jdbc.password
            value: '{{ db_model.pass }}'

    - name: Migrate Repos
      command: mvn flyway:migrate -Djdbc.url={{ db_model.host }} -Djdbc.username={{ db_model.user }} -Djdbc.password={{ db_model.pass }}
      args:
        chdir: '${ { item}}}'
      with_items:
        - /vagrant/persistence

    - name: Compile Repos
      command: mvn clean install {% if item.config is defined %}-Dpath.to.db.config.file={{ item.config }}{% endif %}
      args:
        chdir: '{{ item.repo }}'
      with_items:
        - repo: /vagrant
          config: '{{ db_model_config_file }}'

    - name: Run Tomcat server on port 8080
      shell: mvn spring-boot:run -Dpath.to.db.config.file={{ db_model_config_file }}  </dev/null >/dev/null 2>&1 & sleep 1
      args:
          chdir: /vagrant/rest
